// Generated by the property buffer compiler. DO NOT EDIT!
// source: Homo2.prop

#ifndef HOMO2_PROPERTY_BUFFER_H
#define HOMO2_PROPERTY_BUFFER_H

#include <cctype>
#include <cstdlib>
#include "parallel.h"

namespace Homo2 {

typedef int intE;
typedef unsigned int uintE;

class SSSP_shortestPathLen {
public:
  SSSP_shortestPathLen(size_t n) {
    data = (intE*) malloc(sizeof(intE) * n);
    parallel_for (int i = 0; i < n; ++i) {
      data[i] = 0x3f3f3f3f;
    }
  }
  ~SSSP_shortestPathLen() {
    free(data);
  }
  inline intE operator[] (int i) const { return data[i]; }
  inline intE& operator[] (int i) { return data[i]; }
  intE* data;
};

class SSSP_changed {
public:
  SSSP_changed(size_t n) {
    data = (intE*) malloc(sizeof(intE) * n);
    parallel_for (int i = 0; i < n; ++i) {
      data[i] = 0;
    }
  }
  ~SSSP_changed() {
    free(data);
  }
  inline intE operator[] (int i) const { return data[i]; }
  inline intE& operator[] (int i) { return data[i]; }
  intE* data;
};

class Property {
public:
  size_t n;
  Property(size_t _n): n(_n) {}
  inline SSSP_shortestPathLen* add_shortestPathLen() {
    SSSP_shortestPathLen* shortestPathLen = new SSSP_shortestPathLen(n);
    return shortestPathLen;
  }
  inline SSSP_changed* add_changed() {
    SSSP_changed* changed = new SSSP_changed(n);
    return changed;
  }
};


} // namespace Homo2

#endif // HOMO2_PROPERTY_BUFFER_H
